@extends('layouts.app')
@section('title', 'Program - '.$program->nama)
@section('content')
<nav aria-label="breadcrumb" class="mb-3"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="{{ route('programs.index') }}">Program</a></li><li class="breadcrumb-item active">{{ $program->nama }}</li></ol></nav>
<div class="d-flex justify-content-between align-items-center mb-4"><div><h3 class="fw-bold mb-1">{{ $program->nama }}</h3><p class="text-muted mb-0">Kelola Kegiatan dan Sub Kegiatan dalam Program ini.</p></div><div class="d-flex gap-2"><a href="{{ route('programs.index') }}" class="btn btn-outline-secondary">← Kembali</a><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#addKegiatan">+ Tambah Kegiatan</button></div></div>
@if(session('success'))<div class="alert alert-success alert-dismissible fade show">{{ session('success') }}<button type="button" class="btn-close" data-bs-dismiss="alert"></button></div>@endif
@if(session('error'))<div class="alert alert-warning alert-dismissible fade show">{{ session('error') }}<button type="button" class="btn-close" data-bs-dismiss="alert"></button></div>@endif
@if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif

<div class="card shadow-sm border-0 mb-4"><div class="card-header bg-white py-3 d-flex justify-content-between align-items-center"><div><div class="fw-semibold">📋 Kegiatan</div><div class="small text-muted">Seluruh Kegiatan yang berada di bawah Program {{ $program->nama }}.</div></div><span class="badge text-bg-primary">{{ $program->kegiatans->count() }} Kegiatan</span></div><div class="card-body p-0"><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead class="table-light"><tr><th class="ps-4">Kode</th><th>Kegiatan</th><th>Sub Kegiatan</th><th class="text-end pe-4">Aksi</th></tr></thead><tbody>
@forelse($program->kegiatans as $kegiatan)
<tr><td class="ps-4">{{ $kegiatan->kode ?: '-' }}</td><td class="fw-semibold">{{ $kegiatan->nama }}</td><td><span class="badge text-bg-light border">{{ $kegiatan->subKegiatans->count() }} Sub Kegiatan</span></td><td class="text-end pe-4"><div class="btn-group btn-group-sm"><a class="btn btn-outline-primary" href="#sub-kegiatan-{{ $kegiatan->id }}">Lihat Sub Kegiatan</a><button class="btn btn-outline-secondary" data-bs-toggle="modal" data-bs-target="#editKegiatan{{ $kegiatan->id }}">Edit</button><form method="POST" action="{{ route('programs.kegiatans.destroy', [$program, $kegiatan]) }}" class="d-inline">@csrf @method('DELETE')<button class="btn btn-outline-danger" onclick="return confirm('Hapus Kegiatan ini? Kegiatan yang masih memiliki Sub Kegiatan tidak dapat dihapus.')">Hapus</button></form></div></td></tr>
@empty<tr><td colspan="4" class="text-center text-muted py-5">Belum ada Kegiatan pada Program ini. Klik <strong>Tambah Kegiatan</strong> untuk memulai.</td></tr>@endforelse
</tbody></table></div></div></div>

<div class="card shadow-sm border-0" id="sub-kegiatan"><div class="card-header bg-white py-3 d-flex justify-content-between align-items-center"><div><div class="fw-semibold">🗂 Sub Kegiatan</div><div class="small text-muted">Seluruh Sub Kegiatan dikelompokkan berdasarkan Kegiatan di dalam Program ini.</div></div><span class="badge text-bg-primary">{{ $program->kegiatans->sum(fn($k) => $k->subKegiatans->count()) }} Sub Kegiatan</span></div><div class="card-body">
@forelse($program->kegiatans as $kegiatan)
<div class="border rounded-3 mb-3" id="sub-kegiatan-{{ $kegiatan->id }}"><div class="p-3 bg-light border-bottom d-flex justify-content-between align-items-center"><div><div class="fw-semibold">{{ $kegiatan->nama }}</div><div class="small text-muted">Kode: {{ $kegiatan->kode ?: '-' }}</div></div><button class="btn btn-sm btn-primary" data-bs-toggle="modal" data-bs-target="#addSubKegiatan{{ $kegiatan->id }}">+ Tambah Sub Kegiatan</button></div><div class="table-responsive"><table class="table table-sm table-hover align-middle mb-0"><thead><tr><th class="ps-3">Kode</th><th>Sub Kegiatan</th><th>Target</th><th>Satuan</th><th class="text-end pe-3">Aksi</th></tr></thead><tbody>
@forelse($kegiatan->subKegiatans as $item)
<tr><td class="ps-3">{{ $item->kode ?: '-' }}</td><td class="fw-semibold">{{ $item->nama }}</td><td>{{ $item->target ?? '-' }}</td><td>{{ $item->satuan ?: '-' }}</td><td class="text-end pe-3"><div class="btn-group btn-group-sm"><button class="btn btn-outline-secondary" data-bs-toggle="modal" data-bs-target="#editSub{{ $item->id }}">Edit</button><form method="POST" action="{{ route('kegiatans.sub-kegiatans.destroy', [$kegiatan, $item]) }}" class="d-inline">@csrf @method('DELETE')<button class="btn btn-outline-danger" onclick="return confirm('Hapus Sub Kegiatan ini?')">Hapus</button></form></div></td></tr>
@empty<tr><td colspan="5" class="text-center text-muted py-3">Belum ada Sub Kegiatan.</td></tr>@endforelse
</tbody></table></div></div>
@empty<div class="text-center text-muted py-4">Belum ada Kegiatan. Tambahkan Kegiatan terlebih dahulu.</div>@endforelse
</div></div>

<div class="modal fade" id="addKegiatan" tabindex="-1"><div class="modal-dialog"><form class="modal-content" method="POST" action="{{ route('programs.kegiatans.store', $program) }}">@csrf<div class="modal-header"><h5 class="modal-title">Tambah Kegiatan</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="alert alert-light border small">Program induk: <strong>{{ $program->nama }}</strong></div><div class="mb-3"><label class="form-label">Kode Kegiatan</label><input name="kode" class="form-control"></div><div class="mb-3"><label class="form-label">Nama Kegiatan</label><input name="nama" class="form-control" required></div></div><div class="modal-footer"><button class="btn btn-primary">Simpan Kegiatan</button></div></form></div></div>
@foreach($program->kegiatans as $kegiatan)
<div class="modal fade" id="addSubKegiatan{{ $kegiatan->id }}" tabindex="-1"><div class="modal-dialog"><form class="modal-content" method="POST" action="{{ route('kegiatans.sub-kegiatans.store', $kegiatan) }}">@csrf<div class="modal-header"><h5 class="modal-title">Tambah Sub Kegiatan</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="alert alert-light border small">Program: <strong>{{ $program->nama }}</strong><br>Kegiatan: <strong>{{ $kegiatan->nama }}</strong></div><div class="mb-3"><label class="form-label">Kode Sub Kegiatan</label><input name="kode" class="form-control"></div><div class="mb-3"><label class="form-label">Nama Sub Kegiatan</label><input name="nama" class="form-control" required></div><div class="row"><div class="col"><label class="form-label">Target</label><input name="target" type="number" step="0.01" class="form-control"></div><div class="col"><label class="form-label">Satuan</label><input name="satuan" class="form-control"></div></div></div><div class="modal-footer"><button class="btn btn-primary">Simpan Sub Kegiatan</button></div></form></div></div>
@foreach($kegiatan->subKegiatans as $item)
<div class="modal fade" id="editSub{{ $item->id }}" tabindex="-1"><div class="modal-dialog"><form class="modal-content" method="POST" action="{{ route('kegiatans.sub-kegiatans.update', [$kegiatan, $item]) }}">@csrf @method('PUT')<div class="modal-header"><h5 class="modal-title">Edit Sub Kegiatan</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="mb-3"><label class="form-label">Kode Sub Kegiatan</label><input name="kode" class="form-control" value="{{ $item->kode }}"></div><div class="mb-3"><label class="form-label">Nama Sub Kegiatan</label><input name="nama" class="form-control" value="{{ $item->nama }}" required></div><div class="row"><div class="col"><label class="form-label">Target</label><input name="target" type="number" step="0.01" class="form-control" value="{{ $item->target }}"></div><div class="col"><label class="form-label">Satuan</label><input name="satuan" class="form-control" value="{{ $item->satuan }}"></div></div></div><div class="modal-footer"><button class="btn btn-primary">Simpan Perubahan</button></div></form></div></div>
@endforeach
<div class="modal fade" id="editKegiatan{{ $kegiatan->id }}" tabindex="-1"><div class="modal-dialog"><form class="modal-content" method="POST" action="{{ route('programs.kegiatans.update', [$program, $kegiatan]) }}">@csrf @method('PUT')<div class="modal-header"><h5 class="modal-title">Edit Kegiatan</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="mb-3"><label class="form-label">Kode Kegiatan</label><input name="kode" class="form-control" value="{{ $kegiatan->kode }}"></div><div class="mb-3"><label class="form-label">Nama Kegiatan</label><input name="nama" class="form-control" value="{{ $kegiatan->nama }}" required></div></div><div class="modal-footer"><button class="btn btn-primary">Simpan Perubahan</button></div></form></div></div>
@endforeach
@endsection